### ISSUE TITLE
Feature request: add CORS support in service worker

### ISSUE THREAD

**Issue by EastonLee** [emadda/tabserve#2]
Most websites/servers content can't be loaded across sites, but tabserve service worker can add this feature to bypass browser CORS check.

**Comment by emadda** [comment]
Hey @EastonLee, can you expand on what you mean?

The Tabserve web worker that makes the `fetch` request is still inside the browser, and therefore the browser will still block `fetch` requests to sites that do not return CORS headers.

**Comment by EastonLee** [comment]
I have achieved my goad to bypass CORS check with [this Chrome extension](https://webextension.org/listing/access-control.html). This extension simply adds some CORS related headers in HTTP response to allow almost any requests across sites.

Is it possible for tabserve to have the similar feature, so I don't need to install other extensions and still enjoy across sites requests.

Maybe I'm wrong, if browsers forbid service workers to do the response header modification, correct me, thank you.

**Comment by emadda** [comment]
I think the extension is the right method for you.

As I understand, service workers only intercept requests to the server for the website they are loaded for.

Thanks.
