### ISSUE TITLE
Open source the front end

### ISSUE THREAD

**Issue by Brenden2008** [emadda/tabserve#5]
I love the idea of this project and find it super interesting, I would love to look at how the front end code works and possibly reverse engineer it to pair it with [StackBlitz WebContainers](https://webcontainers.io/) for publicly accessible web servers in the browser.

**Comment by emadda** [comment]
Hey @Brenden2008

The sequence diagram gives an overview:
https://tabserve.dev/#sequence-diagram

The CF web worker shows how the public HTTPS and forwarding requests works:
https://github.com/emadda/worker-tabserve-reverse-proxy

The Tabserve frontend app connects to the CF worker via WebSocket, receives msgpack encoded requests, makes the local request with JS fetch, then sends the response back in a msgpack encoded websocket message.

So I would guess you could re-use the CF worker, and then write a websocket frontend client.

Sorry - I cannot open source the web frontend for now.

Thanks for the interest.
